//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Utils
{
	static public string EnumToString(AssignedSystem penum)
	{
		string enumString = Enum.GetName(typeof(AssignedSystem), penum);
		string firstLetter = enumString [0].ToString ().ToUpper ();
		string restOfString = enumString.Substring(1).ToLower();
		return firstLetter + restOfString;
	}

	public Utils ()
	{
	}
}
